name: Build & Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  validate-abap-transpilation-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./sales
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run pull
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npm test
      - run: sh build-linux.sh
  validate-abap-transpilation-macos:
    runs-on: macos-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./sales
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run pull
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npm test
      - run: sh build-mac.sh
